### ISSUE TITLE
Concurrent Access

### ISSUE THREAD

**Issue by victorstewart** [skarupke/flat_hash_map#24]
I intend to start using your bytell_hash_map in my project, so my question applies to it specifically, but I assume the answer will apply to all your hash maps...

Are concurrent reads from multiple threads thread-safe? I skimmed the find implementation and see no reason why reads would not be.

I (with 99% certainty) assume writes are not.

**Comment by skarupke** [comment]
Writes are not thread safe. Concurrent reads are allowed.
