### ISSUE TITLE
constexpr problem in Visual Studio 2015

### ISSUE THREAD

**Issue by pembeci** [skarupke/flat_hash_map#6]
I am getting an "expression did not evaluate to a constant" error on line 217 in Visual Studio 2015 Update 3:
```c++
213    template<typename T>
214    struct EntryDefaultTable
215    {
216        static constexpr const sherwood_v3_entry_constexpr<T> table[min_lookups] =
217        {
218            {}, {}, {}, sherwood_v3_entry_constexpr<T>::special_end_entry()
219        };
220    };
```
I checked and Microsoft's `constexpr` support may be problematic for some kind of usages. They already fixed some bugs. So I was wondering  if there is a workaround to this piece of code. Another possibility is may be I am missing a compile flag. Thanks.

**Comment by skarupke** [comment]
I got it to compile in VS2015 again. Let me know if it works for you now.

**Comment by pembeci** [comment]
We moved on to a different setup (non VS) so it may be hard for me to try it again but thanks any way.
