### ISSUE TITLE
template_iterator iterator do not always return a value

### ISSUE THREAD

**Issue by Dllieu** [skarupke/flat_hash_map#7]
Hello,

Is it intended?

```c++
            iterator begin()
            {
                for (EntryPointer it = entries;; ++it)
                {
                    if (it->has_value())
                        return { it };
                }

                // No return value here
            }
```

I believe it should at least return ```end()``` or ```cend()``` depending of the constness of the iterator

see https://github.com/skarupke/flat_hash_map/pull/8

**Comment by skarupke** [comment]
The loop has no exit condition, so you can't get down there. The only way to exit the loop is through the return statement. You will always hit the `it->has_value()` case because there is a special entry at the end of the table that stops iteration.
